
# Set 'nord-blue' as custom color palette
palette = 'nord-blue'

format = """
[░▒▓](color1)\
$username\
$os\
$hostname\
[](bg:color2 fg:color1)\
$directory\
[](fg:color2 bg:color3)\
$git_branch\
$git_status\
[](fg:color3 bg:color4)\
$nodejs\
$rust\
$golang\
$php\
$kubernetes\
[](fg:color4 bg:color5)\
$time\
[ ](fg:color5)\
$cmd_duration\
\n$character"""

# Define custom colors
# Nord theme
[palettes.nord-blue]
color1 = '#a0a9cb'
color2 = '#6C98EF'
color3 = '#394260'
color4 = '#212736'
color5 = '#1d2230'

[palettes.nord-purple]
color1 = '#757B9B'
color2 = '#4E65B3'
color3 = '#32343F'
color4 = '#1C1D24'
color5 = '#191A20'

[palettes.nord-green]
color1 = '#A6CEAB'
color2 = '#73E877'
color3 = '#3B5E40'
color4 = '#223523'
color5 = '#1E2F20'

[palettes.nord-tan]
color1 = '#CDC7A2'
color2 = '#E8BA74'
color3 = '#5E543B'
color4 = '#362E22'
color5 = '#2E291D'

[palettes.nord-red]
color1 = '#CCA3A1'
color2 = '#E87478'
color3 = '#5E3E3B'
color4 = '#362222'
color5 = '#2E1E1D'

[directory]
style = "fg:color5 bg:color2"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[character]
error_symbol = " [×](bold red)"
success_symbol = " [╰─λ](bold color2)"

[conda]
symbol = " "

[cmd_duration]
disabled = false
format = "took [$duration]($style)"
style = "fg:color2"
min_time = 1

[dart]
symbol = " "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[fossil_branch]
symbol = " "

[git_branch]
symbol = ""
style = "bg:color3"
format = '[[ $symbol $branch ](fg:color2 bg:color3)]($style)'

[git_status]
style = "bg:color3"
format = '[[($all_status$ahead_behind )](fg:color2 bg:color3)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:color4"
format = '[[ $symbol ($version) ](fg:color2 bg:color4)]($style)'

[guix_shell]
symbol = " "

[haskell]
symbol = " "

[haxe]
symbol = "⌘ "

[hg_branch]
symbol = " "

[hostname]
disabled = false
ssh_only = false
format = "[$hostname ]($style)"
style = "bold bg:color1 fg:color4"
# trim_at = "-"

[java]
symbol = " "

[julia]
symbol = " "

[kubernetes]
format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed green) '

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = ""
style = "bg:color4"
format = '[[ $symbol ($version) ](fg:color2 bg:color4)]($style)'

[os]
disabled = false  
format = "[$symbol]($style)"
style = "bg:color1 fg:color5"

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = "ﲊ "
Illumos = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = " "
Solus = "ﴱ "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "

[php]
symbol = ""
style = "bg:color4"
format = '[[ $symbol ($version) ](fg:color2 bg:color4)]($style)'

[pijul_channel]
symbol = "🪺 "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = ""
style = "bg:color4"
format = '[[ $symbol ($version) ](fg:color2 bg:color4)]($style)'

[scala]
symbol = " "

[spack]
symbol = "🅢 "

[time]
disabled = false
# time_format = "%R" # Hour:Minute Format
time_format = "%T" # Hour:Minute Format
style = "bg:color5"
format = '[[  $time ](fg:color1 bg:color5)]($style)'

[username]
format = "[ $user]($style)"
show_always = true
style_root = "bold bg:color1 fg:color4"
style_user = "bg:color1 fg:color4"

